### ISSUE TITLE
Could not use kdesome in archlinux

### ISSUE THREAD

**Issue by aiwonanjing** [denydias/kdesome#11]
I use antergos to get a kde desktop, and I have done the same as you say, but the awesome desktop told me that it can not find xdg-menu. Please help me to know how could I fix it.

**Comment by denydias** [comment]
I don't know Antergos that well, but [xdg-menu](https://wiki.archlinux.org/index.php/xdg-menu) is a CLI utility. As Antergos is Arch based, you may check if you're able to install xdg-menu from [this package](https://www.archlinux.org/packages/community/any/archlinux-xdg-menu/).

**Comment by aiwonanjing** [comment]
In kubuntu 18.04, I used a software called extra-xdg-menus, and i works(although it has some error too, but it doesn't affect my using).
But in manjaro kde(also an Arch based system), the kdesome told me it cannot find the module local.menu which is the same as I see it from antergos. I have installed the archlinux-xdg-menu (called manjaro-xdg-menu in manjaro).So I cannot even see the menu,

**Comment by aiwonanjing** [comment]
Maybe you can know the solution from [https://gitlab.manjaro.org/profiles-and-settings/desktop-settings/tree/master/community/awesome/skel](url). Manjaro provides a official build for awesome desktop with xfce desktop.

**Comment by aiwonanjing** [comment]
I know that [https://github.com/denydias/kdesome/issues/9](url) has asked the same question, but it is such a difficult question for a new user to lua.

**Comment by denydias** [comment]
`local.menu` is just a xdg-menu generated file with menu entries for the desktop right-click. You can create it at your will or keep it empty/remove the `require("local.menu")` line if you don't use it.

If you decide to create `local.menu` file, [this reply](https://github.com/denydias/kdesome/issues/9#issuecomment-269103233) has more info about its structure.

**Comment by aiwonanjing** [comment]
I am sorry to disturb you again. After I add those two files to local folder, when I start my awesome desktop, it told me it cannot file xdgmenu. I am sure that I have installed archlinux-xdg-menu(manjaro-xdg-menu in manjaro). And there is a bin file called xdg_menu.

**Comment by aiwonanjing** [comment]
I have resolved it by myself, thanks for your help.

**Comment by denydias** [comment]
I'm glad you've sorted out this issue. If you want, you could share the solution you found here so other Arch users may benefit from it.
