### ISSUE TITLE
Awesome can't find local.menu

### ISSUE THREAD

**Issue by MaxG87** [denydias/kdesome#9]
I'm running Debian testing. For the moment I try to start awesome by starting KDE, then killing kwin_x11 and then starting awesome. This gives me some control, e.g. to redirect error messages into a file.

Awesome won't start because it can't find "local.menu". I have installed the package menu-xdg and restarted, but this was only a wild guess. The log is attached. Please don't be confused; the user is named "awesome" as well.

Do you know what I'm doing wrong?

    error while running function
    stack traceback:
    	[C]: in function 'require'
    	/home/awesome/.config/awesome/rc.lua:306: in main chunk
    error: /home/awesome/.config/awesome/rc.lua:306: module 'local.menu' not found:
    	no field package.preload['local.menu']
    	no file './local/menu.lua'
    	no file '/usr/local/share/lua/5.1/local/menu.lua'
    	no file '/usr/local/share/lua/5.1/local/menu/init.lua'
    	no file '/usr/local/lib/lua/5.1/local/menu.lua'
    	no file '/usr/local/lib/lua/5.1/local/menu/init.lua'
    	no file '/usr/share/lua/5.1/local/menu.lua'
    	no file '/usr/share/lua/5.1/local/menu/init.lua'
    	no file '/home/awesome/.config/awesome/local/menu.lua'
    	no file '/home/awesome/.config/awesome/local/menu/init.lua'
    	no file '/etc/xdg/awesome/local/menu.lua'
    	no file '/etc/xdg/awesome/local/menu/init.lua'
    	no file '/usr/share/awesome/lib/local/menu.lua'
    	no file '/usr/share/awesome/lib/local/menu/init.lua'
    	no file './local/menu.so'
    	no file '/usr/local/lib/lua/5.1/local/menu.so'
    	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/local/menu.so'
    	no file '/usr/lib/lua/5.1/local/menu.so'
    	no file '/usr/local/lib/lua/5.1/loadall.so'
    	no file './local.so'
    	no file '/usr/local/lib/lua/5.1/local.so'
    	no file '/usr/lib/x86_64-linux-gnu/lua/5.1/local.so'
    	no file '/usr/lib/lua/5.1/local.so'
    	no file '/usr/local/lib/lua/5.1/loadall.so'
    W: awesome: xerror:881: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
    W: awesome: xerror:881: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
    W: awesome: xerror:881: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
    W: awesome: xerror:881: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
    W: awesome: xerror:881: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
    W: awesome: xerror:881: X error: request=GrabKey (major 33, minor 0), error=BadAccess (10)
    
    (process:3404): GLib-WARNING **: poll(2) failed due to: Die Ressource ist zur Zeit nicht verfügbar.

**Comment by denydias** [comment]
You're doing nothing wrong. As you may imagine, a menu can contain private information. For this reason, I have not included a local menu file.

You can create one by adding a `local` directory with the following files in it:

```
kdesome/local
├── menu.lua
└── rules.lua
```

And for these files, you may add something like above. Of course, you may freely tailor them to better fit your needs.

###  menu.lua

```lua
--[[
     KDEsome awesome WM config
     github.com/denydias/kdesome
     Local menu config
--]]

-- Required libraries and environment
local awful = require("awful")

-- Menu applications
browser1    = "firefox"
pim         = "kontact"
im          = "pidgin"
filemanager = "dolphin"
kdeconf     = "systemsettings"
aweconf     = "kate --new --name aweconf " .. home .. "/.conkyrc " ..
              config_dir .. "/compton.conf " .. theme_dir .. "/theme.lua " ..
              config_dir .. "/local/menu.lua " .. config_dir .. "/local/rules.lua " ..
              config_dir .. "/rc.lua"

-- Submenus
require("xdgmenu")
sys_menu = {
  { "Terminal", terminal, icons .. "/kAwOkenWhite/clear/22x22/apps/terminal.png" },
  { "Configurar KDE", kdeconf, icons .. "/kAwOkenWhite/clear/22x22/apps/kdeapp.png" },
  { "Configurar awesome", aweconf, icons .. "/kAwOkenWhite/clear/22x22/apps/window-manager.png" }}

-- Main Menu
mymainmenu = awful.menu.new({ items = {
  { "Firefox", browser1, icons .. "/kAwOkenWhite/clear/22x22/apps/firefox.png" },
  { "Kontact", pim, icons .. "/kAwOkenWhite/clear/22x22/apps/kontact.png" },
  { "Pidgin", im, icons .. "/kAwOkenWhite/clear/22x22/apps/pidgin.png" },
  { "Kopete", im1, icons .. "/kAwOkenWhite/clear/22x22/apps/kopete.png" },
  { "Dolphin", filemanager, icons .. "/kAwOkenWhite/clear/22x22/apps/file-manager.png" },
  { "Apps", xdgmenu, icons .. "/kAwOkenWhite/clear/22x22/places/folder-script.png" },
  { "Sistema", sys_menu, icons .. "/kAwOkenWhite/clear/22x22/start-here/start-here-slackware1.png" }}})

-- Root menu window (right-click)
root.buttons(awful.util.table.join(
    awful.button({ }, 3, function () mymainmenu:toggle() end)
    )
)
```

### rules.lua

```lua
--[[
     KDEsome awesome WM config
     github.com/denydias/kdesome
     Local rules config
--]]

-- Required libraries
local awful = require("awful")
local beautiful = require("beautiful")

-- Rules
awful.rules.rules = {
    -- All clients will match this rule
    { rule = { },
      properties = { border_width = beautiful.border_width,
                     border_color = beautiful.border_normal,
                     focus = awful.client.focus.filter,
                     keys = clientkeys,
                     maximized_vertical   = false,
                     maximized_horizontal = false,
                     buttons = clientbuttons,
                     size_hints_honor = false } },

    -- Match all new clients, notify name and class (for debug purposes only)
    --{ rule = { },
    --  properties = { },
    --  callback = function(c)
    --                 naughty.notify({title="New Client Debug", text="Name: ".. c.name.."\nClass: ".. c.class})
    --             end },

    -- {{ Application rules
    -- Firefox: all clients in screen 1, tag 1
    { rule = { class = "Firefox" },
      properties = { tag = tags[1][1] } }
}
```
